import asyncio
import os
import sys
import json
from datetime import datetime, timedelta, timezone
from telethon import TelegramClient

# Setup Path
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if BASE_DIR not in sys.path:
    sys.path.append(BASE_DIR)

from get_data.main import fetch_rank_fuse_pipeline, assemble_daily_briefing

async def run_verification():
    print("🧪 Starting Deduplication Verification...")
    
    # 1. Run Pipeline requesting 60 items
    target_count = 60
    print(f"🎯 Target: {target_count} unique items.")
    
    start_time = datetime.now()
    final_items = await fetch_rank_fuse_pipeline(limit=target_count, hours=24) # Fetch 24h to ensure plenty of data
    end_time = datetime.now()
    
    duration = (end_time - start_time).total_seconds()
    
    # 2. Analyze Output
    count = len(final_items)
    print(f"\n📊 Result: Got {count} items in {duration:.2f}s")
    
    if count >= target_count:
        print("✅ SUCCESS: Hit target count.")
    else:
        print(f"⚠️ WARNING: Only got {count}/{target_count} items. (Maybe not enough source data?)")
        
    # 3. Check for obvious duplicates in output (simple text check)
    titles = [item['Category'] + item.get('Original_Text', '')[:20] for item in final_items]
    if len(titles) != len(set(titles)):
        print("❌ FAILED: Exact duplicates found in final output!")
    else:
        print("✅ SUCCESS: No exact duplicates in final output.")
        
    # 4. Assemble Text Content (For Web Display)
    print("\n📝 Assembling Daily Briefing Text...")
    article_quotas = {
        "━━ 一、精选头条 ━━": 10,
        "━━ 二、项目动态 ━━": 15,
        "━━ 三、市场观察 ━━": 25,
        "━━ 四、链上侦探 ━━": 10
    }
    final_content_text = assemble_daily_briefing(final_items, title_prefix="深度日报 (Test)", quotas=article_quotas)
    print(f"📄 Content Length: {len(final_content_text)} chars")

    # 5. Preview Top 5
    print("\n📝 Top 5 Output:")
    for i, item in enumerate(final_items[:5]):
        text_preview = item.get('Fused_Text', item.get('Original_Text', ''))
        print(f"{i+1}. [{item['Category']}] {text_preview[:60]}...")

    # 6. Save verification record
    out_file = os.path.join(BASE_DIR, "tools", "output", f"verification_{int(datetime.now().timestamp())}.json")
    with open(out_file, 'w', encoding='utf-8') as f:
        json.dump(final_items, f, ensure_ascii=False, indent=2, default=str)
    print(f"\n💾 Saved full output to {out_file}")

    # 7. Save to history.json (TEST MODE)
    history_file = os.path.join(BASE_DIR, "data", "history.json")
    try:
        if os.path.exists(history_file):
            with open(history_file, 'r', encoding='utf-8') as f:
                history = json.load(f)
        else:
            history = []
            
        test_entry = {
            "id": f"test_daily_{int(datetime.now().timestamp())}",
            "content": final_content_text, # REAL formatted text
            "title": f"TEST: 币圈深度日报 - {datetime.now().strftime('%Y/%m/%d')}",
            "items": final_items,
            "status": "test", # Marked as test
            "content_type": "article",
            "created_at": datetime.now().isoformat(),
            "note": "Generated by verify_deduplication.py"
        }
        
        # Prepend to history (newest first usually)
        history.insert(0, test_entry)
        
        with open(history_file, 'w', encoding='utf-8') as f:
            json.dump(history, f, ensure_ascii=False, indent=2)
            
        print(f"✅ Saved TEST Article to history.json (ID: {test_entry['id']})")
    except Exception as e:
        print(f"❌ Failed to save to history: {e}")

if __name__ == "__main__":
    asyncio.run(run_verification())
