import os
from . import gen_config as config

class ContentLoader:
    def __init__(self):
        pass

    def get_next_article(self):
        """
        Returns a dictionary representing the article content.
        In a real app, this might fetch from a DB or API.
        """
        return {
            "title": "Automated X Article Test",
            "body": "This is a test article generated by the X Article Automation System.\n\nIt features modular architecture and strategy pattern for browser control.",
            "cover_image": str(config.ASSETS_DIR / "cover_image_1769268577722.png")
        }
